linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - govet
    - misspell
    - nilerr
    - perfsprint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

run:
  timeout: 5m
  # build-tags:
  # - unix

linters-settings:
  gocyclo:
    min-complexity: 16

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
